config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registration' }
    root to: 'pages#home'
    resources :tasks, except: [:index]
    get 'tasks/:id/completed' => 'tasks#completed', as: :completed
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
     can :manage, Task, user_id: user.id
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
	validates_presence_of :title 
	validate :future_completed_date
	validate :validate_due_date
	belongs_to :user 
	validates_presence_of :user

	def self.due_task_notification_cron_job
		tasks=Task.where(' is_completed = ?',false).all
		tasks.each do |t|
			if t.due_date.to_date < Date.today 
				TaskMailer.due_date_passed_mail(t.user,t).deliver
			end
		end
	end
	def self.todays_task_notification_cron_job
		tasks=Task.where(' is_completed = ?',false).all
		tasks.each do |t|
			if t.due_date.to_date == Date.today 
				TaskMailer.todays_due_task_mail(t.user,t).deliver
			end
		end
	end

	private 
	def future_completed_date
		if !completed_at.blank? && completed_at > Date.today
			self.errors.add(:completed_at, "Please enter valid date") 
		end
	end
	def validate_due_date
		if !due_date.blank? &&  due_date < Date.today
			self.errors.add(:due_date, "Please enter valid date") 
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable
  has_many :tasks


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  layout :layout_by_controller 
  protected def layout_by_controller 
     devise_controller? ? 'devise' : 'application' 
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	#Show complete list of 
	def home 
		 @tasks = Task.accessible_by(current_ability)
	end
end

app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController

	private
	 
	  def sign_up_params
	    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	  end
	 
	  def account_update_params
	    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
	  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController  #Task controller to manage tasks
	#create empty task and show task form
	def new
		@task = Task.new
		render :show_form
	end

	#Create task from task form and and persist in db
	def create
		format_task_attributes(task_params)
		@task =Task.new(@updated_params)
		logger.debug "Created Task  #{@task}"
		@task.user = current_user
		authorize! :create, @task
		@task.is_completed=false
		save_task
	end

	#delete the task specified by id parameter
	def destroy
	  @task = Task.find(params[:id]) 
	  @task.destroy 
	  @tasks = Task.accessible_by(current_ability) 
	end 

	#Show task edit form for specified parameter 
	def edit
	  @task = Task.find(params[:id])
	  authorize! :edit, @task
	  render :show_form
	end

	#Update task  specified by id parameter
	def update 
	  logger.debug "Params --------------------------------------- #{params}"

	  logger.debug "task params --------------------------------------#{task_params}"
	  format_task_attributes(task_params)
	  
	  logger.debug "-------------------------------------------------------------"
	  logger.debug "Updated Params  #{@updated_params}"
	  @updated_params[:id]=params[:id]
	  @task = Task.find(@updated_params[:id])
	  logger.debug "#########################"
	  logger.debug "Task found "
	  
	  @task.assign_attributes(@updated_params)
	  authorize! :update, @task
	  @task.is_completed=false
	  save_task
	end

	def completed

		@task = Task.find(params[:id])
		if  @task.is_completed.nil? && !@task.is_completed
			authorize! :edit, @task
			@task.is_completed=true
			@task.completed_at=Date.today
			@task.due_date=DateTime.now
			
		end
			save_task
	end

	private 
	def task_params
		params.require(:task).permit(:title, :description, :completed_at,:due_date,:priority,:id)
	end
	 def save_task 	
	 	logger.debug "Inside save_task"
	 	logger.debug "Completed at #{@task.completed_at}"
	 	if @task.save 
	 		#TaskMailer.new_task_mail(@task.user,@task).deliver
			@tasks = Task.accessible_by(current_ability)
	 		render :create 
	 	else 
	 		render :show_form
	 	end 
	 end
	 #format due date parameter and generate updated parameters to crete task object 
	 def format_task_attributes(task_params)
	 	logger.debug "Inside format task attributes"
		dueDateTime=task_params['due_date'].split(" ")
		logger.debug "due dateAndTime   #{dueDateTime}"
	 	dueDate=dueDateTime.first.split("/")
	 	dueTimes=dueDateTime.last
	 	dueTime=dueDateTime[1].split(":")
	 	 if dueTimes == "PM" && dueTime[0].to_i<12
	 	 	dueTime[0]=dueTime[0].to_i+12
	 	 end
	 	dateAndTime=DateTime.new(dueDate[2].to_i ,  dueDate[0].to_i, dueDate[1].to_i, dueTime[0].to_i, dueTime[1].to_i )
		task_params.store('due_date' ,dateAndTime.to_datetime)
		logger.debug "After change #{task_params[:due_date]}"
		@updated_params=task_params
		@updated_params[:due_date]=dateAndTime.to_datetime
		logger.debug "New Hash #{@updated_params}"
	 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!! 
%html   
  %head     
    %title Todo     
    = stylesheet_link_tag    "application", media: "all"  
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %div.navbar.navbar-inverse.navbar-fixed-top
      %div.container
        %a.navbar-brand TODO Welcome
        %a.navbar-brand=current_user.first_name
        %ul.nav.navbar-nav.navbar-right
          %li.navbar-text=current_user.email
          %li.navbar-link=link_to 'Logout' , destroy_user_session_path, method: :delete
    .container.row-fluid
      .jumbotron
        .span10.offset
          .hero-unit.text-center
            .text-center
              %br
              %strong Add Your To-do tasks and get busy
              %br
              %br
            = link_to 'Add New task', new_task_path, class: 'btn btn-primary', remote: true
    =yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title TODO
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %div.container.row-fluid
      %div.jumbotron
        %div.span10.offset1
          %div.hero-unit.text-center
            %h4
              TODO
            %p
              Welcome 
      %div.row-fluid
        %div.span4.offset4
          =yield

app/views/pages/home.html.haml
#task-list.container  
  = render partial: 'tasks/task_list', locals: {tasks: @tasks}
#modal.modal.fade
      

app/views/tasks/_task_form.html.haml
%div.modal-header
  %h1
    =task.new_record? ? 'New Task' : "Editing task: #{task.title}"  
= simple_form_for task, remote: true do |f|   
  %div.modal-body
    .form-inputs
      = f.label :title
      = f.text_field :title , :class => "form-control" 
      = f.label :description
      = f.text_area :description, :class => "form-control"
      = f.input :due_date , as: :string, input_html: {id:'datetimepicker',class: 'datetimepicker form-control' ,value: task.due_date.present? ? localize(task.due_date,format:'%m/%d/%Y  %H:%M  %p') : nil}
      = f.label :priority
      = f.select :priority ,[["Very High","Very High"],["High", "High"], ["Normal", "Normal"],["Low","Low"]] ,input_html:{class: 'form-control'}
  %div.modal-footer
    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
    = f.submit 'Save', class: 'btn btn-primary'

app/views/tasks/_task_list.html.haml
- if tasks.empty?
  %span.text-warning 
    There are no tasks!   
- else
  / Declare Variable
  -taskList=tasks.all.where('due_date < ?',Date.today).order(created_at: :desc)
  - unless taskList.empty?
    %span.text-warning
      Pending Tasks
    %br
    %br
    %table.table.table-hover.table-bordered.table-responsive.sortable
      %thead
        %tr
          %th Task         
          %th Due Date       
          %th Actions     
      %tbody         
      - taskList.each do |task|
        %tr.danger
          %td               
            %strong= task.title
            %span.label.label-default
              Priority:
              =task.priority            
          %td.text-info= task.due_date
          %td
            = link_to edit_task_path(task), title: 'Edit Task',remote: true do
              %i.glyphicon.glyphicon-edit
            = link_to completed_path(task),title: 'Complete Task', remote: true do
              %i.glyphicon.glyphicon-ok
            =link_to task_path(task),title: 'Delete Task',remote: true,method: :delete ,data: { confirm: "Are you sure you want to delete task : #{task.title}?"} do 
              %i.glyphicon.glyphicon-remove   

  
  %br
  %span.text-warning
    To-do Tasks
  %br
  %br
  %table.table.table-hover.table-bordered.table-responsive.sortable
    %thead
      %tr
        %th Task         
        %th Due Date       
        %th Actions     
    %tbody         
      - tasks.each do |task|
        - unless task.due_date < Date.today
          - unless task.completed_at.nil?
            %tr.success
              %td               
                %strong= task.title   
                %span.label.label-default
                  Priority:
                  =task.priority          
              %td.text-info= task.due_date             
              %td
                = link_to edit_task_path(task),title: 'Edit', remote: true do
                  %i.glyphicon.glyphicon-edit
                = link_to completed_path(task), title: 'Complete Task',remote: true do
                  %i.glyphicon.glyphicon-ok
                =link_to task_path(task),title: 'Delete Task',remote: true,method: :delete ,data: { confirm: "Are you sure you want to delete task : #{task.title}?"} do
                  %i.glyphicon.glyphicon-remove 
          - else
            %tr
              %td               
                %strong= task.title   
                %span.label.label-default
                  Priority:
                  =task.priority          
              %td.text-info= task.due_date             
              %td
                = link_to edit_task_path(task),title: 'Edit', remote: true do
                  %i.glyphicon.glyphicon-edit
                = link_to completed_path(task),title: 'Complete Task', remote: true do
                  %i.glyphicon.glyphicon-ok
                =link_to task_path(task),title: 'Delete Task',remote: true,method: :delete ,data: { confirm: "Are you sure you want to delete task : #{task.title}?"} do
                  %i.glyphicon.glyphicon-remove 

                
                  
      

        

app/views/tasks/create.js.erb
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');
$('#modal').modal('hide'); 

app/views/tasks/destroy.js.erb
$('#task-list').html('<%= j(render partial: 'task_list', locals: {tasks: @tasks})%>'); 

app/views/tasks/edit.js.erb
m = $('#modal'); 
m.html('<%= j(render partial: 'task_form', locals: {task: @task})%>'); 
m.modal('toggle');
 $('#modal').integrateDatepicker();

app/views/tasks/show_form.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task}) %>'); 
m.modal('show');
$('#modal').integrateDatepicker();